name: kelana
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_auth: 
  google_sign_in: 
  cloud_firestore: 
  fluttertoast: 
  image_picker: 
  shared_preferences: 
  firebase_storage: 
  cached_network_image: 
  intl: 
  smooth_star_rating: 

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    # https://unsplash.com/photos/EN2PucB2yhA
  - assets/ronnie-mayo-361348-unsplash.jpg
  # https://unsplash.com/photos/pmH_Y4Qetrk
  - assets/stefan-stefancik-105587-unsplash.jpg
  # https://unsplash.com/photos/5ditmO9_ae0
  - assets/simon-fitall-530083-unsplash.jpg
  # https://unsplash.com/photos/3MNzGlQM7qs
  - assets/anton-repponen-99530-unsplash.jpg
  # https://unsplash.com/photos/CPjkWSD0RM0
  - assets/kevin-cochran-524957-unsplash.jpg
  # https://unsplash.com/photos/T0XLKgpyT_c
  - assets/samsommer-72299-unsplash.jpg
  # https://unsplash.com/photos/twukN12EN7c
  - assets/simon-matzinger-320332-unsplash.jpg
  # https://unsplash.com/photos/8BH_M-53CyA
  - assets/meng-ji-102492-unsplash.jpg
  # https://unsplash.com/photos/tvOvBq90bM0
  - assets/brady-bellini-212790-unsplash.jpg
  - assets/bali.jpg
  - assets/kelana.png
  - assets/wakatobi1.jpg
  - assets/land.jpg
  - assets/water.jpg
  - assets/culture.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
